### ISSUE TITLE
does GET request support Proxy?

### ISSUE THREAD

**Issue by cvley** [gorilla/http#29]

**Comment by elithrar** [comment]
Can you expand on what you mean by proxy? Go’s net/http package has a
ProxyFromEnvironment function that can fetch proxy info for use when
dialing.

**Comment by cvley** [comment]
My use case is that each request has a specified proxy. 

Go's `net/http` does support proxy, but I have to change the Transport of the client with each request before I call `client.Do()` function.

I am looking for a http library that supports to setup proxy in each request, not like `net/http` which I need to change the client transport parameter.

Any suggestions? Thanks.

**Comment by elithrar** [comment]
I’m not aware of a library that does that, because most build on the
familiar http.Transport interface.

Why not write a small lib that exposes a RequestWithProxy(req,
proxyAddress) method that creates custom http.Clients on the fly?

You could even have a map or cache of proxyAddress <=> http.Client to
benefit from connection re-use to the same proxy.

**Comment by cvley** [comment]
@elithrar Thanks for your advice. 😃 

It seems a good idea to write a small custom lib for this.

I will close this issue.
